
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'sneaker_point'
version: '1.0.0'
config-version: 2

profile: 'sneaker_point'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  sneaker_point:
    example:
      +enabled: false
    silver:
      +materialized: view
      +schema: SILVER
    gold:
      +schema: GOLD
      dimensions:
        +materialized: table
      facts:
        +materialized: table
      aggregates:
        +materialized: table

snapshots:
  sneaker_point:
    +target_schema: SNAPSHOTS
    +strategy: timestamp
    +updated_at: updated_at
